// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhwismfptblqftwbkfpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJod2lzbWZwdGJscWZ0d2JrZnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjA5MjcsImV4cCI6MjA2MzkzNjkyN30.sQfn7o5byeX5ppIY6O1CwEah65RvFupW6-emMhoqInk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);